FROM python:3.9-slim

WORKDIR /frontend

COPY . .

RUN pip install --upgrade pip && \
    pip install streamlit==1.29.0 requests==2.31.0 pydantic==2.5.3

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]