version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.7.3-python3.8
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: '46BKJoQYlBmJ9p7mJ8Z9mZk9yL8zJ9vQJ9mZk9yL8zJ9vQ=='
    volumes:
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/dags
        target: /opt/airflow/dags
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/logs
        target: /opt/airflow/logs
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/plugins
        target: /opt/airflow/plugins
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/data
        target: /opt/airflow/data
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username airflow --password airflow --firstname Airflow --lastname Admin --role Admin --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.7.3-python3.8
    build: .
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: '46BKJoQYlBmJ9p7mJ8Z9mZk9yL8zJ9vQJ9mZk9yL8zJ9vQ=='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/dags
        target: /opt/airflow/dags
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/logs
        target: /opt/airflow/logs
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/plugins
        target: /opt/airflow/plugins
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/data
        target: /opt/airflow/data
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/models
        target: /opt/airflow/models
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/results
        target: /opt/airflow/results
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    image: apache/airflow:2.7.3-python3.8
    build: .
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/dags
        target: /opt/airflow/dags
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/logs
        target: /opt/airflow/logs
      - type: bind
        source: /c/Users/galie/itmo_DORA_project/plugins
        target: /opt/airflow/plugins
    command: scheduler

volumes:
  postgres-db-volume: